x2_rules = {
    'Cổ đứng trơn': 'F2.1',
    'Cổ đứng trơn 2 lớp ghim dựng': 'F2.1.1',
    'Cổ đứng trơn 2 lớp (vắt sổ chân cổ, sống cổ)': 'F2.1.1A',
    'Cổ đứng 2 lớp, cổ lót can phối, cạnh cổ có cá cổ': 'F2.1.1B',
    'Cổ đứng trơn 3 lớp (bông tấm)': 'F2.1.2',
    'Cổ đứng có 3 lớp cổ. chân cổ có đáp cúc cất trong cổ': 'F2.1.2A',
    'Cổ đứng có 3 lớp cổ. chân cổ có khoá chân cổ': 'F2.1.2B',
    'Cổ đứng trơn 4 lớp': 'F2.1.3',
    'Cổ chính có  chần trang trí': 'F2.2',
    'Cổ có đáp khoá': 'F2.3',
    'Cổ đứng trơn 2 lớp, có đáp khoá': 'F2.3.1',
    'CỔ PILOT áo 2 lớp': 'F2.3.1A',
    'CỔ PILOT  ÁO 1 LỚP': 'F2.3.1B',
    'Cổ đứng trơn 3 lớp, có đáp khoá': 'F2.3.2',
    'Cổ đứng bản cổ chính có bổ, cổ lót trần trang trí (bông tấm)': 'F2.3.2A',
    'Cổ đứng 2 lớp can cổ chính, cổ lót may phối canh cổ, sống cổ': 'F2.3.2B',
    'Cổ đứng trơn 4+5 lớp có khoá lông vũ (bông vón)': 'F2.3.3',
    'Cổ đứng trơn 4+5 lớp có đáp cúc lông vũ (bông vón)': 'F2.3.3A',
    'Cổ đứng trơn 4+5 lớp không có đáp cổ': 'F2.3.3B',
    'Cổ đứng trơn 4+5 lớp không có đáp cổ, mũ liền cổ': 'F2.3.3C',
    'Cổ đứng trơn 4+5 lớp không có đáp. cổ trần trang trí chính, lót + sống cổ có viền phối': 'F2.3.3D',
    'Cổ đứng trơn 4+5 lớp có đáp cổ,  trần trang trí cổ chính': 'F2.3.3E',
    'Cổ 2,3 lớp có trần trang trí cổ chính + đáp cúc': 'F2.4',
    'Cổ phối (3+4 lớp) bông tấm': 'F2.5',
    'Cổ bẻ có chân (2,3,4 lớp) dựng': 'F2.6',
    'Cổ bẻ không chân (2,3,4 lớp) (can bản cổ)': 'F2.6A',
    'Cổ bẻ không chân (2,3,4 lớp)': 'F2.6B',
    'Cổ đứng có bổ khóa trần (2 đầu cổ can)': 'F2.7',
    'Cổ đứng có bổ khoá 2 viền có hầm': 'F2.7A',
    'Cổ chính nhiều mảnh (có khoá giữa cổ)': 'F2.8',
    'Cổ chính nhiều mảnh': 'F2.9A',
    'Không cổ (mũ liền thân)': 'F2.9',
    'Cổ mũ (2 mảnh) - 1 lớp đường may lộn': 'F2.9.1',
    'Cổ mũ (3 mảnh) - 1 lớp đường may cuốn có oze, dây luồn': 'F2.9.1A',
    'Cổ mũ (3 mảnh)': 'F2.9.2',
    'Cổ mũ (3 mảnh)- 2 lớp có đáp cửa mũ': 'F2.9.2.1',
    'Cổ mũ (3 mảnh)- 2 lớp không có đáp cửa mũ': 'F2.9.2.2',
    'Cổ mũ (3 mảnh) - 3 lớp có đáp cửa mũ': 'F2.9.2.3',
    'Cổ mũ 3 mạnh cửa mũ có đáp, lần lót trần bông vón (ép seam)': 'F2.9.2.3A',
    'Cổ mũ (3 mảnh) - 4,5 lớp có đáp cửa mũ chần ngang lông vũ': 'F2.9.2.4',
    'Cổ mũ (3 mảnh) - 4,5 lớp có đáp cửa mũ bông vón': 'F2.9.2.5',
    'Cổ mũ (3 mảnh) - 4,5 lớp trần ngang có đáp cửa mũ bông vón có dây luồn, ôze có khoá': 'F2.9.2.5A',
    'Cổ mũ (3 mảnh) - 4,5 lớp trần ngang có đáp cửa mũ lông vũ có dây luồn, ôze có khoá': 'F2.9.2.5F',
    'Mũ (3 mảnh) - 4,5 lớp trần ngang có đáp cửa mũ bông vón có dây luồn, ôze đập cúc': 'F2.9.2.5B',
    'Cổ mũ (3 mảnh) - 4,5 lớp ô vuông/quả trám có đáp cửa mũ bông vón có dây luồn, ôze': 'F2.9.2.5C',
    'Cổ mũ (3 mảnh) - 4,5 lớp trần ngang bông vón cửa mũ viền chun': 'F2.9.2.5D',
    'Cổ mũ (3 mảnh) - 4,5 lớp trần ngang có đáp cửa mũ bông vón có dây luồn, ôze': 'F2.9.2.5E',
    'Cổ mũ (2 mảnh) không chần có đáp cửa mũ, cửa mũ có oze, dây luồn': 'F2.9.3',
    'Cổ mũ (3 mảnh) không chần có đáp cửa mũ, cửa mũ có oze, dây luồn, có khoá chân mũ': 'F2.9.3A',
    'Cổ mũ (3 mảnh) không chần có đáp cửa mũ, cửa mũ có oze, dây luồn': 'F2.9.3B',
    'Cổ mũ (3 mảnh) không chần  có đáp cửa mũ, cửa mũ có oze, dây luồn (ghim bông mũ lót)': 'F2.9.3C',
    'Cổ có súp cất mũ': 'F2.9.4',
    'Cổ đứng (bản cổ  chính, lót) can': 'F2.9.5',
    'cổ (bản cổ  chính, lót) can có đáp khoá': 'F2.9.5A'
}

x3_rules = {
    'Nẹp liền có dựng/bông': 'F3.1',
    'Nẹp rời có dựng/bông': 'F3.2',
}

x5x6_rules = {
    'Túi cơi (1 lớp)': 'F5.1',
    'Túi cơi có khoá nằm trên đường may (1 lớp)': 'F5.1A',
    'Túi cơi có nằm trên đường may (1 lớp)': 'F5.1B',
    'Túi cơi (áo 2,3 lớp)': 'F5.2',
    'Túi cơi  nổi (áo 2,3 lớp)': 'F5.2A',
    'Túi cơi (4+5 lông vũ - bông vón)': 'F5.3',
    'Túi cơi có khoá (1lớp)': 'F5.4',
    'Túi cơi có khoá (2+3 lớp)': 'F5.5',
    'Túi cơi có khoá (4 +5 lớp)': 'F5.6',
    'Túi cơi có nắp (2+3 lớp)': 'F5.7',
    'Túi cơi có nắp (4+5 lớp)': 'F5.8',
    'Túi 2 viền (1 lớp)': 'F5.9',
    'Túi 2 viền (2+3 +4 bông tấm)': 'F5.10',
    'Túi 2 viền (4+5) lông vũ - bông vón)': 'F5.11',
    'Túi 2 viền có khoá (1lớp)': 'F5.12',
    'Túi 2 viền có khoá, có hầm (1lớp)': 'F5.12A',
    'Túi 2 viền có khoá (2+3 lớp)': 'F5.13',
    'Túi 2 viền có khoá (4 +5 lớp)': 'F5.14',
    'Túi 2 viền có khoá, hầm (2+3 lớp)': 'F5.15',
    'Túi 2 viền có khoá, hầm (4+5 lớp)': 'F5.16',
    'Túi 2 viền có nắp (2+3 lớp)': 'F5.17',
    'Túi 2 viền có nắp (4+5 lớp)': 'F5.18',
    'Túi cơi phối': 'F5.19',
    'Túi khoá trần (hở răng+hầm) bổ trên thân áo 1 lớp': 'F5.20',
    'Túi khoá trần (hở răng+hầm) bổ trên thân áo 2,3,4 lớp': 'F5.20A',
    'Túi khoá trần BỔ TRÊN THÂN TÚI ỐP': 'F5.20B',
    'Túi khoá nằm trên đường may  đề cúp (áo 1 lớp)': 'F5.21',
    'Túi khoá nằm trên đường may cầu ngực (áo 1 lớp)': 'F5.21A',
    'Túi cơi nằm trên đường may': 'F5.22A',
    'Túi cơi liền thân nằm trên đường may': 'F5.22C',
    'Túi cơi có khoá nằm trên đường may (2 +3 lớp)': 'F5.22D',
    'Túi khoá nằm trên đường may (2 +3 lớp)( có mí diễu miệng túi)': 'F5.22',
    'Túi khoá nằm trên đường may (2 +3 lớp)(  miệng túi kiểu khoá giọt lệ)': 'F5.22G',
    'Túi khoá nằm trên đường may (2 +3 lớp) KHÔNG CÓ ĐỀ CÚP': 'F5.22E',
    'Túi khoá có 2 viền nằm trên đường may sườn (2 +3 lớp)': 'F5.22B',
    'Túi khoá có 2 viền nằm trên đường may cầu ngực  (2 +3 lớp)': 'F5.22F',
    'Túi ốp không nắp (đáy vuông)': 'F5.23',
    'Túi ốp có khoá nằm trên thân túi': 'F5.23A',
    'Túi ốp kiểu dáng dao xây': 'F5.23B',
    'Túí (miệng túi hàm ếch liền thân)': 'F5.23C',
    'Túi ốp không nắp may mặt trong áo 1 lớp': 'F5.23D',
    'Túi ốp có nắp (đáy vuông)': 'F5.24',
    'Túi ốp có nắp có nhám (đáy vuông)': 'F5.24A',
    'Túi hộp 1 lớp có nắp  đáy vuông': 'F5.25',
    'Túi hộp nhiều lớp có nắp đáy vuông': 'F5.26',
    'Túi ốp tay có khóa (1 túi)': 'F5.27',
    'Túi ốp TT có khóa': 'F5.27A',
    'Túi đựng áo': 'F5.28',
    'Túi đựng áo MIỆNG TÚI CÓ KHOÁ': 'F5.28A',
    'Túi khoá trần có hầm cắt': 'F5.29',
    'túi nằm trên đường may, miệng túi viền chun': 'F5.30'
}

x7_rules = {
    'Chần tay áo': 'F7.1',
    'Chần tay liền': 'F7.1.1',
    'Chần ngang tay áo -bông tấm': 'F7.1.1.1',
    'Chần ngang tay áo lần lót - bông tấm': 'F7.1.1.1A',
    'Chần ô vuông/quả trám tay áo - bông tấm': 'F7.1.1.2',
    'Chần ô vuông/quả trám tay áo - bông tấm lót': 'F7.1.1.2A',
    'Chần ngang tay áo - lông vũ': 'F7.1.1.3',
    'Chần ngang tay áo - lông vũ TAY LÓT': 'F7.1.1.3A',
    'Chần ô vuông tay áo - lông vũ': 'F7.1.1.4',
    'Chần ngang tay áo - bông vón': 'F7.1.1.5',
    'Chần sóng tay áo - bông vón': 'F7.1.1.5A',
    'Chần ô vuông/quả trám tay áo - bông vón': 'F7.1.1.6',
    'Tay áo có đường bổ': 'F7.1.2',
    'Tay áo có chèn tay + cá có cúc- chần ngang - bông tấm': 'F7.1.2.1',
    'ghim chèn tay trước, sau lần chính': 'F7.1.2.1D',
    'Tay áo có 1 chèn tay, chần ngang-bông tấm': 'F7.1.2.1A',
    'Tay áo có tay to trần ngang bông tấm. chèn tay trước, sau ghim bông': 'F7.1.2.1B',
    'Tay áo có chèn tay trước, sau , chần ngang-bông tấm': 'F7.1.2.1C',
    'Tay áo bổ dọc + ngang (không trần) có cá': 'F7.1.2.2',
    'Tay áo có chèn tay (2 lớp) không  cá (1 chèn) có vắt sổ': 'F7.1.2.2A',
    'Tay áo có chèn tay (1 lớp) cuốn viền có cá (1 chèn)': 'F7.1.2.2F',
    'Tay áo bổ dọc (1 lớp) cuốn viền': 'F7.1.2.2G',
    'Tay áo có chèn tay trước, sau (1 lớp)': 'F7.1.2.2K',
    'Tay áo có 1 chèn  (1 lớp)': 'F7.1.2.2H',
    'Tay áo có chèn tay (2 lớp) + ngang  không cá': 'F7.1.2.2B',
    'Tay áo có chèn tay, cửa tay có xẻ tra măng séc (2 lớp) không  cá (1 chèn)': 'F7.1.2.2C',
    'Tay áo có chèn tay, có chiết (2 lớp) không  cá (1 chèn)': 'F7.1.2.2D',
    'Tay áo có chèn trước, chèn sau (ép seam)': 'F7.1.2.2E',
    'Tay áo có chèn tay + cá có nhám - chần ngang - bông vón': 'F7.1.2.3',
    'Tay áo có chèn tay -  chần ngang - bông vón': 'F7.1.2.3A',
    'Tay áo có chèn tay chính chần ngang, mang to không chần. lần lót mang to chần mang nhỏ không trân - bông vón': 'F7.1.2.3C',
    'Tay áo có chèn tay -  ô vuông - bông vón': 'F7.1.2.3B',
    'Tay áo có chèn tay + cá có nhám - chần ngang - lông vũ': 'F7.1.2.4',
    'Tay áo có chèn tay + cá đập cúc - chần ngang - lông vũ': 'F7.1.2.4A',
    'Tay áo có chèn tay  chần ngang - lông vũ': 'F7.1.2.6',
    'Chiết khửu tay (4 chiết)': 'F7.1.2.5'
}

x8_rules = {
    'Cửa tay gập liền có nhám thấm': 'F8.1',
    'Cửa tay gập liền': 'F8.2',
    'Cửa tay đáp rời': 'F8.2A',
    'Cửa tay đáp rời có chun không cá': 'F8.2B',
    'Cửa tay đáp rời, có chun, có nhám': 'F8.2C',
    'Cửa tay bo': 'F8.3',
    'Cửa tay bo - áo 1 lớp': 'F8.3A',
    'Cửa tay chun': 'F8.4',
    'Cửa tay viền chun (2 lớp)': 'F8.5',
    'Cửa tay viền chun (1 lớp)': 'F8.5A',
    'Cửa tay may lộn có diễu bản to cửa tay': 'F8.6',
    'Cửa tay may lộn có không diễu bản to cửa tay': 'F8.6A',
    'Cửa tay măng séc có xẻ': 'F8.7',
    'Cửa tay măng séc KHÔNG XẺ': 'F8.7C',
    'Cửa tay măng séc, có đáp chắn gió': 'F8.7B',
    'Cửa tay măng séc, cài cá cửa tay (có nhám)': 'F8.7A',
    'Cửa tay  có thép tay giống áo sơ mi': 'F8.8',
    'Cửa tay có  đáp, có chắn gió may với bo': 'F8.9'
}

x10_rules = {
    'Cụm thân trước lót': 'F11.2',
    'Thân trước lót có ve nẹp, không túi': 'F11.2.1',
    'Thân trước lót có ve nẹp, 2 bên có túi ốp': 'F11.2.2',
    'Thân trước lót không ve nẹp, 2 bên có túi ốp (ghim 3 cạnh sườn, nẹp, gấu)': 'F11.2.2A',
    'Thân trước lót không ve nẹp, có túi ốp': 'F11.2.2B',
    'Thân trước lót có ve nẹp, 2 bên có túi ốp có chun miệng túi': 'F11.2.3',
    'Thân trước lót có ve nẹp, 2 bên có túi ốp có nhám miệng túi': 'F11.2.4',
    'Thân trước lót có ve nẹp, 1 bên có túi ốp có khoá': 'F11.2.4A',
    'Thân trước lót có ve nẹp, có túi cơi': 'F11.2.5',
    'Thân trước lót có ve nẹp, có túi 2 viền': 'F11.2.6',
    'Thân trước lót có ve nẹp, có túi cơi có khóa': 'F11.2.7',
    'Thân trước lót có ve nẹp, có túi 2 viền khóa': 'F11.2.8',
    'Thân trước lót có ve nẹp, có túi  khóa trần': 'F11.2.9',
    'Thân trước lót không có ve nẹp, có túi  khóa trần': 'F11.2.9A',
    'Thân trước lót không ve nẹp, có túi 2 viền khóa': 'F11.2.9B',
    'Thân trước lót có đề cúp': 'F11.2.11',
    'Thân trước lót can ngang thân trước - cầu ngực lót': 'F11.2.12',
    'Thân trước lót túi  khóa trần may vào ve lần lót': 'F11.2.13',
    'Thân trước lót có túi cơi khoá lằm ve nẹp/thân trước lót': 'F11.2.14',
    'Tay lót có chèn tay (1 chèn) vắt sổ': 'F11.2.10',
    'Thân sau lót có đề cúp (vắt sổ)': 'F11.2.13',
    'Lắp ráp lần lót': 'F12',
    'Chắp vai con lót': 'F12.1',
    'Tra tay lót': 'F12.2',
    'Chắp sườn bụng tay lót + đặt mác': 'F12.3',
    'Chắp vai con lót (Vắt sổ)': 'F12.1A',
    'Tra tay lót (Vắt sổ)': 'F12.2A',
    'Chắp sườn bụng tay lót + đặt mác (Vắt sổ)': 'F12.3A',
    'Chắp sườn lót + đặt mác': 'F12.4',
    'Áo nhiều lớp (tay raglan) (Vắt sổ)': 'F12.5'
}

x13_rules = {
    'Gấu suông': 'F9.1',
    'Gấu gập liền': 'F9.1.1',
    'Gấu may lộn': 'F9.1.1 A',
    'Gấu gập liền có chun': 'F9.1.1 B',
    'Gấu gập liền có ôze + dây luồn': 'F9.1.2',
    'Gấu đáp rời có ôze + dây luồn': 'F9.1.3',
    'Gấu đáp rời không có ôze': 'F9.1.4',
    'Gấu đáp rời không có ôze (1 lớp)': 'F9.1.4A',
    'Gấu bo': 'F9.2',
    'Gấu bo không có đầu đai': 'F9.2.1',
    'Gấu bo không có đầu đai - 1 LỚP': 'F9.2.1A',
    'Gấu bo có đầu đai bằng vải chính': 'F9.2.2 A',
    'Gấu đai trần chun 2 bên sườn có đầu đai bằng vải chính': 'F9.2.2 B',
    'Gấu viền chun': 'F9.2.3',
    'viền chun cả gấu, nẹp liền 1 lớp': 'F9.2.3A',
    'Gấu đáp rời , may lộn cả nẹp': 'F9.2.4A',
    'Gấu đáp rời có chun 2 bên sườn ': 'F9.2.4',
    'Gấu bo chun bằng vải có đầu đai': 'F9.2.5',
    'Gấu có đai liền': 'F9.2.7',
    'Gấu có đai rời': 'F9.2.7A',
    'Gấu đáp rời có chun không cá': 'F9.2.7C',
    'Gấu may lộn có đáp gấu (không diễu bản to gấu)': 'F9.2.7B',
    'May xẻ sườn': 'F9.2.8',
    'Gấu đáp rời không có ôze có xẻ sau': 'F9.2.9'
}

x14_rules = {
    'Mũ 2 mảnh': 'F4.1',
    'Mũ 2 mảnh 1 lớp (may cuốn đáp khóa)': 'F4.1.1',
    'Mũ 3 mảnh có đáp cửa mũ có dây luồn, chân mũ đập cức - 1 lớp': 'F4.1.1A',
    'Mũ 3 mảnh có đáp cửa mũ, chân mũ đập cức - 1 lớp': 'F4.1.1B',
    'Mũ 2 mảnh 1 lớp (may lộn đáp khóa )': 'F4.1.2',
    'Mũ 2 mảnh 1 lớp (may lộn, khoá )': 'F4.1.3',
    'Mũ 2 mảnh áo 2 lớp có đáp khóa': 'F4.1.4',
    'Mũ 2 mảnh áo 2 lớp không có đáp khoá, có oze': 'F4.1.4A',
    'Mũ 2 mảnh không có đáp khoá (Mũ 2 lớp) cửa muc có đáp bong luồn dây': 'F4.1.5',
    'Mũ 3 mảnh': 'F4.2',
    'Mũ 3 mảnh có đáp khóa - áo 2 lớp': 'F4.2.1',
    'Mũ 3 mảnh có khóa  có đáp cửa mũ, dây luồn ôze- áo 2 lớp': 'F4.2.1A',
    'Mũ 3 mảnh đập cúc chân mũ có đây luồn ôze của mũ   - áo 2 lớp': 'F4.2.1B',
    'Mũ 3 mảnh có đáp khóa, đáp cửa mũ- 3 lớp, bông tấm không chần': 'F4.2.2',
    'Mũ 3 mảnh có đáp cửa mũ- 3 lớp, bông tấm không chần': 'F4.2.2A',
    'Mũ 3 mảnh có đáp khóa- 3 lớp, bông tấm chần ngang, cửa mũ có ôze, dây luồn': 'F4.2.3',
    'Mũ 3 mảnh 2 lớp cửa mũ viền': 'F4.2.4',
    'Mũ 3 mảnh 2 lớp cửa mũ may lộn': 'F4.2.5',
    'Cổ Mũ 3 mảnh có đáp cửa mũ, có dây luôn (bông vón)': 'F4.2.6',
    'Cổ Mũ 3 mảnh có đáp cửa mũ, có viền cửa mũ, khoá chân mũ (bông vón)': 'F4.2.6A',
    'Mũ 3 mảnh có đáp cửa mũ, đáp cúc, có dây luôn (lông vũ)': 'F4.2.7',
    'Mũ 3 mảnh có đáp cửa mũ, có khoá chân mũ, có dây luôn (lông vũ)': 'F4.2.7A',
    'Mũ 4 mảnh': 'F4.3',
    'Mũ 4 mảnh - khoá, 3 lớp không chần bông tấm, có oze, dây luồn cửa mũ': 'F4.3.1',
    'Mũ 4 mảnh - có tai mũ dán nhám chân mũ đập cúc': 'F4.3.2',
    'Mũ 4 mảnh cửa mũ lưỡi trai/đáp cửa mũ  - có tai mũ đập cúc': 'F4.3.3'
}