x2_rules = {
    'Cạp rời có chung cả vòng, có khuyết luồn dây, có cạp lót': 'E11.1',
    'Cạp rời có chung cả vòng': 'E11.1A',
    'Cạp rời có chun cả vòng, có khuyết luồn dây': 'E11.1B',
    'Cạp liền có chun cả vòng, có khuyết luồn dây': 'E11.1C',
    'Cạp rời âu thường, 2 lớp chính lót đầu cạp vuông, có mác cạp lót': 'E11.1D',
    'Cạp rời âu thường, 2 lớp chính lót đầu cạp vuông': 'E11.2',
    'Cạp rời có chun cả vòng, có oze luồn dây, mác cạp lót': 'E11.2A',
    'Cạp rời âu thường đầu cạp vuông, có chun thân sau': 'E11.2B',
    'Cạp rời âu thường đầu cạp vuông, có cá 2 bên sườn có nhám': 'E11.2C',
    'Cạp rời âu thường đầu cạp vuông': 'E11.3',
    'Cạp rời âu thường đầu cạp vuông, có ốp che chun cạp': 'E11.3A',
    'Cạp rời âu thường đầu cạp vuông, viền chân cạp lót, mác cạp lót 1': 'E11.3B',
    'Cạp liền có 1 lót cạp ( cửa quần may khoá giọt lệ)': 'E11.4',
    'Cạp rời âu thường đầu cạp vuông, viền chân cạp lót, mác cạp lót 2': 'E11.5',
    'Cạp rời âu thường đầu cạp vuông, viền chân cạp lót, mác cạp lót 3': 'E11.5A',
    'Cạp rời chun cả vòng, cạp chỉnh lót bọc chân cạp lót, mác cạp': 'E11.5B',
    'Cạp rời âu thường đầu cạp vuông, can đầu cạp, bọc chân cạp lót': 'E11.5C',
    'Cạp rời âu thường đầu cạp vuông, có chun 2 bên sườn': 'E11.6',
    'Cạp rời âu thường đầu cạp vuông, mác cạp lót': 'E11.6A',
    'Cạp rười âu thường đầu cạp quai nhê, mác cạp chính': 'E11.6B',
    'Cạp rời có chun có đáp đầu cạp trước': 'E11.6C',
    'Cạp rời thường đầu cạp vuông có chun 2 bên': 'E11.6D',
    'Cạp rời thường đầu cạp vuông cuốn viền chân cạp lót may mác': 'E11.6E',
    'Cạp rời thường đầu cạp vuông có chun 2 bên cuốn viền chân cạp lót may mác': 'E11.6F',
    'Cạp rời thường đầu cạp vuông, chun thân sau, viền lót cạp trước': 'E11.6G',
    'Cạp rời thường đầu cạp vuông cạp 4 mảng, viền chân cạp lót': 'E11.6H'
}

x3_rules = {
    'Túi chéo đáp rời': 'E7.1',
    'Túi chéo đáp rời dọc lật': 'E7.1A',
    'Túi chéo đáp rời dọc rẽ': 'E7.1B',
    'Túi chéo đáp rời dọc rẽ có nắp': 'E7.1C',
    'Túi chéo đáp rời dọc rẽ, có mác': 'E7.1D',
    'Túi chéo đáp rời dọc rẽ, có lõi viền miệng túi': 'E7.1E',
    'Túi chéo đáp liền': 'E7.2',
    'Túi chéo đáp liền dọc rẽ, có mác': 'E7.2A',
    'Túi chéo đáp liền dọc rẽ, lót may lộn vắt sổ, có mác': 'E7.2B',
    'Túi dọc lật, mí diễu dọc': 'E7.3',
    'Túi dọc rẽ/lật': 'E7.3A',
    'Túi dọc rẽ/lật, có mác': 'E7.3B',
    'Túi chéo dọc rẽ/ lật, có mác': 'E7.3C',
    'Túi dọc rẽ': 'E7.4',
    'Túi hàm ếch, lót túi may lộn': 'E7.5',
    'Túi hàm ếch, lót túi vắt sổ': 'E7.5A',
    'Túi trước cơi': 'E7.6',
    'Túi trước cơi có khóa': 'E7.6A',
    'Túi trước 2 viền có khoá, có hầm': 'E7.7',
    'Túi ốp đùi có khóa có hầm': 'E7.7A',
    'Túi trước 2 viền có khóa có hầm': 'E7.7B',
    'Túi trước 2 viền có khóa có hầm (bổ khuân)': 'E7.7C',
    'Túi trước cơi xuôi có khóa': 'E7.8',
    'Túi trước cơi xuôi': 'E7.8A',
    'Túi cơi 2 viền có khoá': 'E7.9',
    'Túi điện thoại cơi xuôi': 'E7.9A',
    'Túi trước khoá trần': 'E7.10',
    'Túi trước khóa trần có hầm': 'E7.10A',
    'Túi đùi khóa trần (bổ khuân)': 'E7.10B',
    'Túi đùi khóa trần có khuân (bổ khuân)': 'E7.10C',
    'Túi trước khóa trần có hầm (bổ khuân)': 'E7.11',
    'Túi chéo khóa trần có hầm (bổ khuân)_1 túi': 'E7.11A',
    'Túi chéo đáp rời có khóa': 'E7.12',
    'Túi chéo đáp rời có khóa (bổ cầu mông với đáp sau)': 'E7.12A',
    'Túi chéo khóa trần có hầm (bổ khuân)': 'E7.12B',
    'Túi chéo đáp rời khóa trần': 'E7.12C',
    'May túi đồng hồ': 'E7.13',
}

x4_rules = {
    'Túi hậu cơi xuôi, lót may lộn, có dây khuyết': 'E9.1A',
    'Túi hậu cơi ngược có khóa': 'E9.1B',
    'Túi hậu cơi xuôi, lót may mác, may lộn': 'E9.1C',
    'Túi hậu cơi ngược có khóa, nằm dưới đường cầu mông': 'E9.2',
    'Túi hậu cơi ngược có khóa, nằm trên đường cầu mông': 'E9.2A',
    'Túi hậu cơi ngược có khóa, bổ khuân': 'E9.2B',
    'Túi hậu cơi ngược có khóa, nằm dưới đường cầu mông, bổ khuân': 'E9.2C',
    'Túi hậu 2 viền có khóa, túi nằm dưới đường cầu mông': 'E9.2D',
    'Túi cơi ẩn có khóa, cơi túi nằm trên đường may cầu mông': 'E9.2E',
    'Túi hậu cơi ngược có khóa nằm trên đường bổ thân sau': 'E9.2F',
    'Túi hậu cơi xuôi, túi nằm dưới đường can cầu mông, bổ khuân': 'E9.2G',
    'Túi hậu cơi ngược túi nằm dưới đường can cầu mông, miệng túi may nhám': 'E9.2H',
    'Túi hậu 2 viền, lót may lộn': 'E9.3',
    'Túi hậu 2 viền, lót vắt sổ': 'E9.3A',
    'Túi hậu 2 viền có khóa': 'E9.4',
    'Túi hậu 2 viền có khóa, bổ khuân': 'E9.5',
    'Túi hậu khóa trần, bổ hầm': 'E9.5A',
    'Túi hậu khóa trần, có hầm': 'E9.6',
    'Túi hậu khóa trần, có hầm, bổ khuân 1': 'E9.6A',
    'Túi hậu khóa trần, có hầm, bổ khuân 2': 'E9.6B',
    'Túi hậu 2 viền có khóa có hầm': 'E9.7',
    'Túi hậu 2 viền có khóa có hầm, bổ khuân': 'E9.7A',
    'Túi hậu ốp, đáy nhọn': 'E9.8',
    'Túi dao xây': 'E9.8A',
    'Túi hậu ốp, đáy nhọn, thân túi may đường trang trí': 'E9.8B',
    'Túi hậu ốp đáy nhọn miệng túi có khóa trần': 'E9.8C',
    'Túi trước ốp, đáy vuông có đường diễu trang trí (túi thợ xây)': 'E9.8D',
    'Túi ốp có nắp, đáy vuông': 'E9.9',
    'Túi hậu ốp đáy vuông, nắp túi tròn, miệng túi may nhám': 'E9.9A',
    'Túi hậu 2 viền có nắp, đính cúc khuyết': 'E9.10'
}

x5_rules = {
    'Túi ốp đùi vát góc có nắp': 'E8.1',
    'Túi ốp đùi không nắp': 'E8.1A',
    'Túi ốp đùi đáp vuông có nắp': 'E8.1B',
    'Túi ốp đùi vông có đô, có nắp': 'E8.1C',
    'May đáp ốp gấu trước': 'E8.1D',
    'Túi ốp nhỏ vát góc trên túi ốp đùi': 'E8.1E',
    'Túi ốp đùi vát góc có nắp (nắp dập 1 cúc)': 'E8.1F',
    'Túi ốp đùi đáy nhọn có nắp (có phối)': 'E8.1G',
    'Túi ốp đùi vuông, thân túi có ly, có nắp': 'E8.1H',
    'Túi ốp đùi đáy nhọn, thân túi bổ, có nắp': 'E8.1J',
    'Túi ốp đùi vát góc có nắp, thân túi bổ túi 2 viền có khoá (2 túi)': 'E8.2',
    'Túi ốp gối vát góc không nắp': 'E8.2A',
    'Túi ốp đùi vát góc có nắp, thân túi bổ túi 2 viền có khoá (1 túi)': 'E8.2B',
    'Túi đùi 2 viền có khoá, hầm, ghim lót túi thấm (bổ khuân)': 'E8.3',
    'Túi đùi 2 viền có khoá, hầm, lót may lộn, có đường diễu trang trí miệng túi (bổ khuân)': 'E8.3A',
    'Túi đùi 2 viền có khoá, hầm, lót may lộn (bổ khuân)': 'E8.3B',
    'Túi đùi 2 viền có khóa, lót may lộn': 'E8.3C',
    'Túi đùi 2 viền có khóa có hầm, lót nay lộn': 'E8.3D',
    'Túi đùi khóa trần, lót túi may lộn diễu lộ chính (bổ khuân)': 'E8.4',
    'Túi đùi 2 viền có khóa, miệng túi bổ trên lót, lót dán trên thân (chắp dọc)': 'E8.4A',
    'Túi đùi 2 viền có khóa, miệng túi bổ trên lót, lót dán trên thân': 'E8.4B',
    'Túi đùi 2 viền có khóa, lót may lộn ghim thấm lần chính': 'E8.4C',
    'Túi hộp vát góc có đô, có nắp': 'E8.5A',
    'Túi hộp có 2 viền có khóa': 'E8.5B',
    'Túi hộp có nắp (1 túi)': 'E8.5C',
    'Túi đùi có súp đáy vuông, có nắp đáy nhọn': 'E8.5D',
    'Túi đùi có súp 2 viền có khóa đáy vát góc, có nắp vuông': 'E8.5E',
    'Túi đùi có súp đáy vát góc, có nắp vuông': 'E8.5F',
    'Nắp túi giả': 'E8.5G',
    'Túi đùi có súp có đô, đáp vát góc, có nắp túi đáy nhọn': 'E8.5H',
    'Túi đùi có súp đáy vát góc, có nắp đáy nhọn, thân túi có túi ốp nhỏ': 'E8.5J',
    'Túi đùi có súp đáy vát góc, có náp vát góc': 'E8.5K',
    'Túi đùi có súp đáy vuông, có nắp đáy vuông': 'E8.5L',
    'Túi đùi có súp đáy vuông, có nắp đáy vuông (nắp túi có khuyết cúc)': 'E8.5Z',
    'Túi đùi có súp đáy tròn, nắp túi đáy tròn có lõi viền lé': 'E8.5X',
    'Túi đùi có súp đáy vuông, có nắp đáy nhọn, miệng túi có nhám': 'E8.5V',
    'Túi đùi ốp miệng túi có viền khóa, thân túi bổ ngang': 'E8.5N',
    'Túi hậu có đô đáy vát góc, có nắp vuông, miệng túi may nhám': 'E8.5M',
    'Túi đùi bổ cơi ngược có khóa, lót ghim thấm lần': 'E8.6',
    'Túi đùi cơi có khóa, lót ghim thấm lần chính (lớp lót là gập đường may mì trái)': 'E8.6A',
    'Túi đùi cơi có khóa, lót ghim thấm lần chính (lót may lộn diễu)': 'E8.6B',
    'Túi cơi đùi có khóa (lót túi may lộn diễu)': 'E8.6C',
    'Túi cơi đùi có khóa, có nắp túi nhọn, lót may lộn ghim thấm lần': 'E8.6D',
    'Túi cơi nổi, lót may lộn': 'E8.7',
    'Túi đùi cơi nổi, lót may lộn': 'E8.7A',
    'Túi cơi sau': 'E8.8',
    'Túi hậu cơi xuôi, lót may lộn (cơi có may dây phản quang)': 'E8.8A',
    'Túi đùi 2 viền có khóa có hầm, lót túi may lộn': 'E8.9',
}

x6_rules = {
    'Cửa quần khoá giọt lệ': 'E6.1',
    'Cửa quần có khoá đáp liền': 'E6.2',
    'Cửa quần có khoá đáp rời': 'E6.3',
    'Cửa quần đáp rời có khóa viền chân đáp, đũng lật': 'E6.3A',
    'Cửa quần đáp rời có khóa, đũng lật': 'E6.3B',
    'Cửa quần của quần nhiều lớp': 'E6.4'
}

x10_rules = {
    'May bổ ngang ống, vắt sổ chập': 'E10.1A',
    'May cầu mông cới TS, vắt sổ chập': 'E10.1B',
    'May bổ ngang ống': 'E10.1C',
    'May đũng trước sau, cầu mông HC': 'E10.1D',
    'May cầu mông với TS có viền lé': 'E10.1E',
    'May cầu mông cới TS có túi trang trí': 'E10.1F',
    'May bổ gối': 'E10.1G',
    'May cầu mông với TS, diễu': 'E10.1H',
    'May cầu mông với TS, cầu mông có bổ dọc': 'E10.1J',
    'May bổ gối ngang, có mác': 'E10.1K',
    'May bổ gối trước, sau mí diễu': 'E10.1L',
    'May bổ ngang trước sau mí diễu': 'E10.1Z',
    'May bổ gối trước sau có mác': 'E10.1X',
    'May bổ ngang TT, TS vắt sổ chập mí diễu': 'E10.1V',
    'May phối dọc dàng, vắt sổ chập': 'E10.1N',
    'May dây phản quang': 'E10.1M',
    'May đệm mông, đệm gối trước': 'E10.1W',
    'May súp chắn gió, may dây phản quang gối': 'E10.1R',
    'May dây phản quang dọc': 'E10.1T',
    'May dọc vắt sổ chập mí diễu': 'E10.2',
    'May dọc mí diễu': 'E10.2A',
    'May dàng': 'E10.2B',
    'May phối dàng+vắt sổ': 'E10.2C',
    'May đáp đũng với dàng trước sau+mí': 'E10.2D',
    'May dọc may phối dàng, vắt sổ chập': 'E10.2E',
    'May trang trí đáp dọc+vắt sổ': 'E10.2F',
    'May dọc, may dọc với phối+vắt sổ': 'E10.2G',
    'May đũng trước sau+vắt sổ chập': 'E10.2H',
    'May dàng trước': 'E10.2K',
    'May dọc, vắt sổ chập': 'E10.2L',
    'May phối dàng, chắp dọc+vắt sổ': 'E10.2Z',
    'May trang trí dọc+vắt sổ': 'E10.2X',
    'May dọc+vắt sổ chập': 'E10.2V',
    'May dọc, vắt sổ chập+mí diễu': 'E10.2N',
    'May phối dàng trước sau+mí diễu': 'E10.2M',
    'May dây dập cucsTT, TS': 'E10.2Q',
    'May đệm mông, đệm gối': 'E10.2W',
    'May cầu mông+mí diễu': 'E10.2R',
    'May ốp đáp dọc': 'E10.2T'
}